### ISSUE TITLE
Don't show jobs in Spark UI

### ISSUE THREAD

**Issue by IvanGuardado** [SingularitiesCR/spark-docker#7]
I'm launching a spark cluster using the provided docker file and it's working perfect (thanks a lot for that!) but I can't see any job running/completed in the Spark UI.

I'd like to see them because you can know what Spark is doing under the hood in a more legible way.

Can anyone help me with this?

**Comment by fjhoelsg** [comment]
If you are using a compose file similar to the one specified in the README, the Web UI for the master is available at port `8080`. If you wish to access the Web UI for the worker add a port directive to map port `8081` in the worker specification; however, if you do this the worker service cannot be scaled.

Another option would be to define several services as workers and map the ports.

**Comment by IvanGuardado** [comment]
Finally the problem was the way I was submitting the application. It was launching the job in local mode, that's the reason I didn't see anything in the UI. For anyone who needed this is how I run it:

**docker-compose.yml**
```yaml
version: "2"

services:
  master:
    image: singularities/spark
    command: start-spark master
    hostname: master
    ports:
      - "6066:6066"
      - "7070:7070"
      - "8080:8080"
      - "50070:50070"
    volumes:
      - ./target/scala-2.11:/opt/hdfs

  worker:
    image: singularities/spark
    command: start-spark worker master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    volumes:
      - ./target/scala-2.11:/opt/hdfs
    links:
      - master
```

**Submit**
```bash
docker exec sparkexperiments_master_1 spark-submit --deploy-mode cluster --master spark://master:6066 /opt/hdfs/simple-project_2.11-1.0.jar
```
